baseurl: "https://curious-electric.com/w/v2/"
languageCode: "en-us"
title: "Curious Electric"
theme: "ce_normal"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
# canonifyURLs: false

# whoha ... this is already default!
taxonomies:
   tag: "tags"
   category: "categories"

# [taxonomies]
#   tag = "tags"
#   category = "categories"


# sectionPagesMenu: "lazymains"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

# menu:
#   main:
#     - name: Home
#       url: ""
#       weight: 1
#       identifier: "home"
#     - name: About
#       url: "/about/"
#       weight: 2
#       identifier: "about"
#     - name: Categories
#       url: "categories/"
#       weight: 3
#       identifier: "categories"
#     - name: Tags
#       url: "tags/"
#       weight: 4
#     - name: RSS
#       url: "index.xml"




languages:
  en:
    languageName: "EN"
    weight: 1
  de:
    languageName: "DE"
    params:
      navigation:
        help: Hilfe
    weight: 2


params:
  description: "Curious Electric is a creative engineering studio turning problems into products — with meaning, love, and brain."
  footer: "&copy; Curious Electric GmbH 2017 - {Year}"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false